### ISSUE TITLE
Have a global export (scope page + scope site + global data)

### ISSUE THREAD

**Issue by gwynnbleiidd** [Asqatasun/Asqatasun#79] opened 2016-03-01 10:48 UTC
Add pdf/csv export for this page.
This good page for test full site :)

**Comment by gwynnbleiidd** [comment] 2016-03-02 11:21
I will add is expanded a bit later that wants to be seen.
Now I try to collect all thoughts in a single whole)

**Comment by mfaure** [comment] 2016-03-04 14:53
Hi @gwynnbleiidd you're right, there is no global export or site-wide export. That could be a contribution.

**Comment by dzc34** [comment] 2016-03-06 20:24
@mfaure  why did you close this issue if  it could be a contribution ?

**Comment by mfaure** [comment] 2016-03-07 12:29
@dzc34 because the issue is "solved" : feature not existent by now.

**Comment by mfaure** [comment] 2016-03-08 16:43
@dzc34 you're right, I leave it open with the Feature Request flag

**Comment by dzc34** [comment] 2017-09-17 16:44
added to #175 and closed

**Closed** 2017-09-17 16:45 UTC
Labels: type: feature request
