### ISSUE TITLE
Rgaa3 rule 10.1.2 and "Pinned Tab icon for Safari"

### ISSUE THREAD

**Issue by dzc34** [Asqatasun/Asqatasun#102] opened 2016-04-03 19:52 UTC
## Observed behavior
a page that uses this code `<link rel="mask-icon" href="/favicon.svg" color="#990000">`
for  "Pinned Tab icon for Safari" 
- https://yoast.com/dev-blog/safari-pinned-tab-icon-mask-icon/
- https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/pinnedTabs/pinnedTabs.html

![selection_001](https://cloud.githubusercontent.com/assets/6709977/14234550/ec0458f4-f9e5-11e5-9a90-ab1430516fcd.png)

## Expected behavior
![selection_002](https://cloud.githubusercontent.com/assets/6709977/14234561/43bc006a-f9e6-11e5-9afc-b5969b0f719c.png)

## Steps to reproduce the behavior
audit a page that uses this code `<link rel="mask-icon" href="/favicon.svg" color="#990000">`
	
eg : 
- http://blog.iconfactory.com/2015/11/the-new-favicon/
- https://yoast.com/dev-blog/safari-pinned-tab-icon-mask-icon/

**Comment by mfaure** [comment] 2016-04-03 22:00
Not sure to agree this is a bug. Using the attribute `color` is against one major principle of accessibility, which is separating content from styling, a.k.a. CSS. 

Moreover, this is [NOT valid as the W3C validator says](https://validator.w3.org/nu/?doc=http%3A%2F%2Fwww.mecatrouve.com%2F): 

> Attribute `color` not allowed on element `link` at this point.

Apple is making dirty things, (hope) they will fix it. You may report this bug to Apple :)

So for me, this is not a bug and should be a WONTFIX.

**Comment by dzc34** [comment] 2016-04-03 22:04
hum, hum @mfaure !

**Comment by mfaure** [comment] 2016-04-05 16:18
Many tools are making crap, but that's not a reason to change the behaviour of an analysis tool like Asqatasun.  Please do report bugs to those tools. Thank you for your understanding :)

**Closed by mfaure** 2016-04-05 16:18 UTC
Labels: Rule : RGAA 3, type: bug
